### PR TITLE
support illuminate/support 9.x (Laravel 9.x)

### PR DESCRIPTION
**Pull request by jonnott**

### CODE REVIEW

**Comment by jonnott** [comment]
Don't think Laravel 9.0 beta likes this package .. get lots of `PHP Fatal error:  Uncaught Error: Object of type Illuminate\Session\Store is not callable` whenever it is used..

**Comment by jonnott** [comment]
@landrok @JeffreyWay

**Comment by JeffreyWay** [comment]
Thanks. Already merged as part of a separate PR.

**Comment by jonnott** [comment]
Ah, thanks @laravel-shift then ;)

Are you planning a release to coincide with L9 launch?

**Pull request closed without merging**
