### PR TITLE
Allowing multiple messages

### PR DESCRIPTION
**Pull request by diogogomeswww**
Allow for multiple flash messages.
But only allowing one overlay message.

### CODE REVIEW

**Comment by fredbradley** [comment]
I really want this pull request to be approved and added to the next update!

**Comment by diogogomeswww** [comment]
@laracasts don't know if Jeffrey wants this feature or not.

**Comment by JeffreyWay** [comment]
Can you all confirm that this works perfectly? I don't have time at the moment to fully test it, but can merge + tag it if we're good to go here.

**Comment by diogogomeswww** [comment]
@JeffreyWay can't confirm that ALL works perfectly :). But all my tests are passing, and I have one application where I'm using this fork.

But if any issues appear, I will fix them.

**Pull request closed without merging**
