### PR TITLE
Changed curly brackets {{ }} => {!! !!}

### PR DESCRIPTION
**Pull request by Shonetow**

### CODE REVIEW

**Comment by zsitro** [comment]
+1

**Comment by chafreaky** [comment]
Is this going to be merged?

Thanks for this great package!

**Comment by Shonetow** [comment]
I don't think so. And it doesn't have.

If you need to modify the flash message partials, you can run:
`php artisan vendor:publish`
The two package views will now be located in the `app/views/packages/laracasts/flash/' directory.

... or ...

You can try this alternative: https://github.com/willishq/laravel5-flash

**Comment by chafreaky** [comment]
Thank you. Ended up making changes locally.

**Comment by JeffreyWay** [comment]
Merged in a different PR. A couple things here don't need to be escaped. (Sorry for delay!)

**Pull request closed without merging**
