### PR TITLE
Added Full (Optional) Localization Support

### PR DESCRIPTION
**Pull request by mknooihuisen**
This PR enables localization in your flash messages by making them use the lang blade directive under the hood.  Both localization formats in Laravel 5.4 (Short key and JSON files) are supported. 

My main goal with this was to maintain existing functionality. Monolingual applications can continue to use this package as they always have, and can later add support for other languages simply by adding appropriate locale.json files.

This also addresses issue #35  See my updated readme for details.

### CODE REVIEW

**Comment by JeffreyWay** [comment]
This is useful, but I'd prefer to keep the package as simple as possible. Feel free to fork it with your changes.

**Comment by mknooihuisen** [comment]
I can certainly do that, but can you tell me what you find is adding complexity?  My first goal was making sure the existing syntax would still work.  The only change is that it will respect language files if the project already has them.

**Comment by jeff-h** [comment]
I would love this added. I guess it's just a small subset of laravel sites overall that need i18n but for me this looks very useful.

There are two kinds of possible complexity here:

* developer experience using the package
* the package code

If the existing syntax is unchanged, then the DX is fine. Is the new code complex? (sorry, I'm too new to Laravel to comment on that).

**Comment by mknooihuisen** [comment]
@jeff-h Since @JeffreyWay recommended it, I'll put the fork on packagist and post back here as soon as I get a chance.  If you're in a hurry, I wrote a [Code Review discussion](https://laracasts.com/discuss/channels/code-review/localized-laracasts-flash-package) on Laracasts about the PR, that also shows how to use it in your projects.

- The only syntax change comes if you're using translation strings with parameters `(i.e. "Hello, :name")` , which I added to the documentation in my fork/PR.  All other syntax is unchanged.
- As for the code complexity, I added a vendor lang file to address issue #35 (which I suppose could be removed), but otherwise, I think my changes only cleaned up the code, which is the main reason I'd like Jefrey's thoughts.

If you're going to use my fork as it stands, know that it currently supports all of Laravel's [Localization](https://laravel.com/docs/5.4/localization) **except** `trans_choice`.  It also does not yet include any of the PR's Jeffrey merged today

**Pull request closed without merging**
