### PR TITLE
Clear flash notification session after display

### PR DESCRIPTION
**Pull request by srmklive**
This PR adds functionality to automatically clear flash notification session after it is rendered. Sometimes the session keeps getting displayed, if the user presses a back button.

### CODE REVIEW

**Comment by ricardovigatti** [comment]
I think this is necessary, but i don't think that putting on the view is the best approach. Have any other suggestion for a place to insert this code?

**Comment by srmklive** [comment]
@ricardovigatti you cant do it anywhere in controller. As the flash session is displayed only once, and it will be somewhere in your layout file. So it makes sense to clear it instantly after display.

**Comment by nelson6e65** [comment]
Maybe using `pull` instead directly...

```php
$value = $request->session()->pull('key', 'default');
```

https://laravel.com/docs/5.1/session

**Comment by JeffreyWay** [comment]
Pull could be good. PR?

**Comment by ricardovigatti** [comment]
The message still being displayed after the user hit "back" on the browser, even using pull or forget.

**Comment by srmklive** [comment]
@JeffreyWay Are the new changes good enough to be merged?

**Comment by ricardovigatti** [comment]
@srmklive i'm facing an FatalErrorException:

`syntax error, unexpected '=', expecting ')'`

**Comment by JeffreyWay** [comment]
I'll pull down the changes today and see if that all works properly.

**Comment by ricardovigatti** [comment]
Check yout code at: 

`@if (!empty($flash_notification = session()->pull('flash_notification', '')))`

should be:

`@if ($flash_notification = session()->pull('flash_notification', ''))`

**Comment by srmklive** [comment]
@ricardovigatti Just checked my changes locally. I didn't run into a fatal error exception.

**Comment by srmklive** [comment]
@ricardovigatti You will only display a flash session unless some task has been completed successfully. Take use registration. You will only set flash message, if the user has been created successfully not when the user has been logged in successfully. 

Your implementation might be wrong. I have used this package in a separate application & haven't been able to replicate the issues you mentioned.

**Comment by ricardovigatti** [comment]
maybe, but i'm only using it to display crud form notifications, like saving a form.

**Comment by JeffreyWay** [comment]
This doesn't seem to work on my end. Here is what I tried:

- Flash a message and then redirect somewhere.
- See that the flash message does display.
- Click on a random link to go to a new page
- Press "Back" to go back. 
- I *still* see the flash message.

I don't exactly know why that's the case, though. It shouldn't do that.

**Comment by srmklive** [comment]
@JeffreyWay I think one should set flash session based on some flag. Like when a user registers, or logs into a site. It could be like:

```
// If the user is logged in. redirect to /home
if (!empty(auth()->user()->id))
    return redirect('/home');

// All the data posted is validated, and user is created
$user = new App\User();
$user->name='John Doe';
$user->email='john@example.com';
$user->save();

if ($user->id) {
flash('Your account has been created!', 'success');
}
```

Something like the above make sense to display flash message in this scenario. Its an individual choice to decide where flash messaging works best. I don't see it as a error here.

**Comment by ricardovigatti** [comment]
I'm starting to think this is a common behavior on browsers. If i'm right, we should let the way it is.

**Comment by srmklive** [comment]
@ricardovigatti Its the logical behavior. Its not a browser issue. Its how you write a block of code in a certain scenario. In one case, it may give a different result in another one entirely different. Its just how you implement something in a certain scenario. I don't see anything wrong with what @JeffreyWay has implemented it here. We should be smart enough to know, where it all makes sense to use it properly & without any issues.

**Comment by ricardovigatti** [comment]
Ok, no worries. I made my tries and i tested both solutions provided by nelson and you, unfortunately without luck... hope we can solve this!

**Pull request closed without merging**
